# Generated by Django 2.2.1 on 2022-10-01 15:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(verbose_name=ckeditor.fields.RichTextField),
        ),
    ]
